name: Release Assets

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Build and pack for linux-amd64
        run: GOOS=linux GOARCH=amd64 go build -o nmap-formatter && tar -czvf nmap-formatter-linux-amd64.tar.gz nmap-formatter
      - name: Build and pack for windows-amd64
        run: GOOS=windows GOARCH=amd64 go build -o nmap-formatter.exe && zip nmap-formatter-windows-amd64.zip nmap-formatter.exe
      - name: Build and pack for macos-amd64
        run: GOOS=darwin GOARCH=amd64 go build -o nmap-formatter && zip nmap-formatter-darwin-amd64.zip nmap-formatter
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nmap-formatter-linux-amd64.tar.gz
            nmap-formatter-windows-amd64.zip
            nmap-formatter-darwin-amd64.zip
